name: Wii Build

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: devkitpro/devkitppc:latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install compiled dependencies
        run: |
          pacman -S --noconfirm devkitPPC libogc ppc-zlib ppc-libpng ppc-freetype ppc-libjpeg-turbo ppc-mxml wii-dev

      - name: Compile source code
        run: |
          make


